fix: compilation quirk with vs2019
This should work around the issue with building with VS2019, where
LuaMod.cpp(2206) fails with "error C3493: 'i' cannot be implicitly
captured because no default capture mode has been specified," which
I assume is a MSVC quirk, as it doesn't make sense otherwise.